---
title: "RIVUR - IGLL5 association study" 
output: html_document 
---

```{r output, eval = F, echo = F}
output:
  knitrBootstrap::bootstrap_document:
    theme: default
    highlight: sunburst
    theme.chooser: TRUE
    highlight.chooser: TRUE
```

```{r setting, message = FALSE, echo=FALSE}
# output:
#   knitrBootstrap::bootstrap_document:
#     theme.chooser: T
#     highlight.chooser: FALSE
#     menu: F
#     title: "IGLL5 repor
library(agricolae)
library(xlsx)
library(car)
library(knitr)
library(xtable)
library(dplyr)
library(ggplot2)
library(reshape2)
library(magrittr)
library(gridExtra)
library(gmodels)
library(psych)
library(tabplot)
opts_chunk$set(dev=c("svg"), 
              fig.height = 4, fig.width = 14)
opts_chunk$set(fig.show="hold")
opts_chunk$set(warning=F, message = FALSE, echo=F, results='asis')
opts_chunk$set(bootstrap.thumbnail.size='col-md-12', 
               bootstrap.thumbnail = T,
               bootstrap.panel = T)

# source("/Users/DL/Documents/R project/Memphis - Copy Number Variation/Functions/myFunction.R")
 
```

```{r functions, echo=F}
science_theme = theme(panel.grid.major = element_line(size = 0.4, color = "grey"),
                      axis.line = element_line(size = 0.5, color = "black"), 
                      legend.position = "bottom", 
#                       legend.position = c(0.85, 0.85),
                      plot.title = element_text(lineheight=.8, size = 10,  face="bold"),
                      text = element_text(size = 14))  

plt_box <- function(df, y, x){
        ggplot(df, aes_string(y = y, x = x)) +
                geom_boxplot(aes_string(fill = x)) +
                scale_y_continuous() +
                theme_bw() +
                science_theme+
                scale_fill_brewer(palette = 1)
}

plt_prop <- function (data, x, fill) {
        TABLE_FUN = eval(parse(text = paste0("table(data$", x, ", data$", fill, ")"))) 
        data_prop = prop.table(TABLE_FUN,2) %>% data.frame
        names(data_prop) = c(x, fill, "Proportion")
        
        ggplot(data_prop, aes_string(x = x, y = "Proportion", fill = fill))+
                geom_bar(stat = "identity", col = "black", position = "dodge")+
                scale_x_discrete()+
                theme_bw() + 
                science_theme +
                scale_fill_brewer(palette = 1)
}

plt_ecdf <- function (data, x, group) {
        ggplot(data, aes_string(x = x, col = group)) + 
                geom_line(stat = "ecdf", size = 1) +
#                 scale_x_discrete()+
                ylab("Cumulative Proportion") +
                theme_bw() + 
                science_theme+
                scale_color_brewer(palette = 1)
}

plt_triple <- function (data = l5, gene = "COPY.NBS.ROUND", va) {
        data = data[!is.na(data[va])&!is.na(data[gene]), ]
        p = list()
        lapply(seq_along(va), function (i) plt_box(data, "DDCT.MEAN", va)) -> p[1]
        lapply(seq_along(va), function (i) plt_prop(data = data, x = gene, fill = va)) -> p[2]
        lapply(seq_along(va), function (i) plt_ecdf(data, gene, va)) -> p[3]
        do.call(grid.arrange, c(p, list(nrow = 1, ncol =3)))
}

```


```{r data_load_preprocessing, cache=T, message = FALSE, echo=F, results='asis'}

# l5 <- read.xlsx("/Users/DL/Dropbox-work/My work-not sync/Protocol/Protocol Memphis/RIVUR data/RIVUR Spreadsheets/RV111201 A1A3 and Array Master Factors.xls", sheetIndex = 1, header = T, stringsAsFactors = T) %>% tbl_df

l5 <- read.csv("/Users/DL/Dropbox-work/My work-not sync/Protocol/Protocol Memphis/IGLL5/Raw data/IGLL5-grand_table(cali = J).csv", header = T, stringsAsFactors = T) %>% tbl_df

sampleInfo = read.xlsx("/Users/DL/Dropbox-work/My work-not sync/Protocol/Protocol Memphis/RIVUR data/RIVUR Spreadsheets/RV111201 A1A3.xls", sheetIndex = 1, header = T, stringsAsFactors = T) %>% tbl_df

knum_ = sub("^ |-D$|A$|B$|-DNA-LCL| -$", "", sampleInfo$Knum.Original)
knum = sub("^ |-D$|A$|B$|-DNA-LCL| -$", "", knum_)
sampleInfo$knum = knum

l5 = merge(l5, sampleInfo, by.x = "RUID", by.y = "knum", all = T)
names(l5) = toupper(names(l5))
l5 = l5[l5$DDCT.SEM<0.5 & !is.na(l5$DDCT.MEAN), ]


l5$TXGROUP_LABEL = recode(l5$TXGROUP, 
                             "'A' = 'TMP/SMZ'; 
                              'P' = 'Placebo'
                             ")
l5$TF02_LABEL = recode(l5$TF02, 
                             "1 = 'Treatment Failure'; 
                              0 = 'No Treatment Failure'
                             ")
l5$RACE0102_LABEL = recode(l5$RACE0102, 
                             "1 = 'White'; 
                              2 = 'Black';
                              3 = 'Asian';
                              4 = 'Hawaiian/Pacific Islander ';
                              5 = 'American Indian/Alaskan';
                              6 = 'Other';
                              7 = 'Mixed';
                              8 = 'Missing'
                             ")

l5$dtCHR_CONST = unclass(l5$CHR_CONST1302) - unclass(l5$CHR_CONST0102)

l5$dtCHR_CONST_LABEL = recode(l5$dtCHR_CONST, 
                             "-1 = 'Better'; 
                               0 = 'No Change';
                               1 = 'Worse'
                             ")

```
## Data summary
```{r summary - plot, fig.height = 7, fig.width = 10}
par(mfrow = c(2,3))
hist(l5$AGE0101, xlab = "Age",breaks = 20, main = "")
plot(as.factor(l5$RACE0102_LABEL), breaks = 7, xlab = "Race", main = "")
plot(factor(l5$SEX0101), xlab = "Sex", main = "")
hist(l5$COPY.NBS.ROUND, xlab = "IGLL5.Copy.Nbs", breaks = 12, main = "")
plot(l5$TXGROUP_LABEL, xlab = "Treatment group assignment")
plot(as.factor(l5$TF02_LABEL), xlab = "Treatment failure")
```

## Correlation
### Gender
```{r sex}
va <- c("SEX0101")
lapply(seq_along(va), function(i) plt_triple(va = va[i])) %>% invisible
```

### Chronic constipation
```{r dtCHR_CONST_LABEL}
va <- c("dtCHR_CONST_LABEL")
lapply(seq_along(va), function(i) plt_triple(va = va[i])) %>% invisible
```

## Grade and laterality (left/right/both) of vesicoureteral reflux
### Highest grade of reflux for right ureter
```{r VR_3R_1301}
l5$VR_3R_1301_LABEL = recode(l5$VR_3R_1301, 
                             " 0 = NA; 
                               1:2 = 'Low';
                               3:4 = 'High'
                             ")
l5$VR_3R_0101_LABEL = recode(l5$VR_3R_0101, 
                             " 0 = NA; 
                               1:2 = 'Low';
                               3:4 = 'High'
                             ")

va <- c("VR_3R_0101_LABEL", "VR_3R_1301_LABEL")
sapply(seq_along(va), function(i) plt_triple(va = va[i])) %>% invisible


```
